const char * token_map[] = 
{
    "EOF",
    "ARRAY",
    "AUTO",
    "BOOLEAN",
    "CHAR",
    "ELSE",
    "FALSE",
    "FOR",
    "FUNCTION",
    "IF",
    "INTEGER",
    "PRINT",
    "RETURN",
    "STRING",
    "TRUE",
    "VOID",
    "WHILE",
    "OPEN_PARENTHESIS",
    "CLOSE_PARENTHESIS",
    "OPEN_BRACKET",
    "CLOSE_BRACKET",
    "OPEN_BRACE",
    "CLOSE_BRACE",
    "POST_INC",
    "POST_DEC",
    "SUB",
    "NE",
    "LOGICAL_NOT",
    "EXP",
    "MULT",
    "DIV",
    "REMAINDER",
    "ADD",
    "LE",
    "LT",
    "GE",
    "GT",
    "EQ",
    "ASSIGNMENT",
    "LOGICAL_OR",
    "LOGICAL_AND",
    "COMMA",
    "QUESTION",
    "COLON",
    "SEMICOLON",
    "INTEGER_LITERAL",
    "IDENTIFIER",
    "CHARACTER_LITERAL",
    "STRING_LITERAL",
    "STRING ERROR",
    "IDENTIFIER ERROR",
    "SCAN ERROR"
};
const int token_map_len = sizeof(token_map) / sizeof(const char *);
